# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
   projectFolder: 'website'
   buildFolder: 'website/build'

stages:
- stage: Development
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: BuildTest
    steps:
    - script: cd $(projectFolder) && npm install
      displayName: 'Install dependencies'
    - script: cd $(projectFolder) && npm run build
      displayName: 'Build'
    - script: cd $(projectFolder) && npm test -- --coverage
      displayName: 'Test'

  - job: ArchiveRelease
    steps:
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: $(buildFolder)
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/release.zip'
        includeRootFolder: true
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/release.zip'

- stage: QA
  dependsOn: Development
  condition: succeeded('Development')
  pool:
    vmImage: ubuntu-latest
    environment: Experimental environment
  jobs:
  - job: Placeholder
    steps:
    - script: echo "Hello World"
