# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

parameters:
  - name: runQATests
    default: false
    values:
    - true
    - false

variables:
   projectFolder: 'website'
   buildFolder: 'website/build'
   qualityGateThreshold: $(Thresholds.codeCoverage)
   pat: $(PAT.marcopat)

stages:
- stage: Development
  pool:
    vmImage: windows-latest
  jobs:
  - job: Development
    steps:
    - script: echo Hi > helloworld.txt
      displayName: 'BS'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'connection'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: 'az storage blob generate-sas --account-name itsectorfeupexample --container-name vhds --name blob --permissions acdrw --expiry 2023-05-08 --auth-mode login --as-user > sas.txt'
        powerShellErrorActionPreference: 'continue'
    - script: echo %cd% && type sas.txt
      displayName: Debug
    - task: PowerShell@2
      inputs:
        filePath: 'variable.ps1'
        arguments: -Pat '$pat'
    - task: AzureFileCopy@3
      inputs:
        SourcePath: 'helloworld.txt'
        azureSubscription: 'connection'
        Destination: 'AzureBlob'
        storage: 'itsectorfeupexample'
        ContainerName: 'vhds'
        CleanTargetBeforeCopy: true
        outputStorageContainerSasToken: 'se=2023-05-08&sp=racwd&sv=2021-06-08&sr=b&skoid=30e7551b-48a9-4842-871f-58030a36e838&sktid=f06ed7e8-2a33-433c-8e90-69f6fba89365&skt=2023-05-05T15%3A10%3A51Z&ske=2023-05-08T00%3A00%3A00Z&sks=b&skv=2021-06-08&sig=4rDob3UvwSAu0ioF9Z8eC0bBrCIQ%2BbRxMiFTdujZTy8%3D'

    - script: cd $(projectFolder) && npm install
      displayName: 'Install dependencies'
    - script: cd $(projectFolder) && npm run build
      displayName: 'Build'
    - script: cd $(projectFolder) && npm run test -- --onlyChanged --coverage --coverageThreshold='{"global":{"branches":"$(qualityGateThreshold)","functions":"$(qualityGateThreshold)","lines":"$(qualityGateThreshold)","statements":"$(qualityGateThreshold)"}}'
      displayName: 'Partial Test Suite' 
    - script: cd dotNetServices && for d in */; do (cd "$d" && dotnet publish -r win-x64 --output OutputExe --self-contained -c Release /p:PublishSingleFile=true /p:AssemblyName="mydotnet_${d%/}" && pwd); done
      displayName: 'dotNet Publish'
    - script: cd dotNetServices && mkdir -p ../save && for d in */OutputExe/; do (mkdir -p ../save/$d && cd "$d" && cp -r * ../../../save/$d ); done  
      displayName: Gathering Published Executables
    
    - task: CopyFiles@2
      inputs:
        Contents: |
          website/build/**
          save/**
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: Select Release Files

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: $(Build.ArtifactStagingDirectory)
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/release.zip'
        includeRootFolder: true
      displayName: Zip Release Files
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/release.zip'
      displayName: Artifact Release

- stage: QA
  dependsOn: Development
  condition: succeeded('Development')
  pool:
      vmImage: ubuntu-latest
      environment: Experimental environment
  jobs:
  - job: QATesting
    steps:
    - script: cd $(projectFolder) && npm install
      displayName: 'Install dependencies'
    - script: cd $(projectFolder) && npm run build
      displayName: 'Build'
    - script: cd $(projectFolder) && npm run test -- --coverage --coverageThreshold='{"global":{"branches":"$(qualityGateThreshold)","functions":"$(qualityGateThreshold)","lines":"$(qualityGateThreshold)","statements":"$(qualityGateThreshold)"}}'
      displayName: 'Full Test Suite'
    - script: cd $(projectFolder) && npm run mutation
      displayName: Mutation Testing
    condition: ${{parameters.runQATests}}
  - job: Approval
    displayName: "Manual Approval"
    pool: server
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 60
        inputs:
          notifyUsers: 'E6022@itsector.pt'
          instructions: 'Release'
          onTimeout: reject