# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  projectFolder: 'website'
  buildFolder: 'website/build'

steps:
- script: cd $(projectFolder) && npm install
  displayName: 'Install dependencies'
- script: cd $(projectFolder) && npm run build
  displayName: 'Build'
- script: cd $(projectFolder) && npm test -- --coverage
  displayName: 'Test'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: $(buildFolder)
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/release.zip'
    includeRootFolder: true

## Publish the zip file
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/release.zip'