# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- new-website

pool:
  vmImage: ubuntu-latest

variables:
  projectFolder: 'website'
  buildFolder: 'website/build'

steps:
- script: pushd $(projectFolder) && npm install && popd
  displayName: 'npm install'
- script: pushd $(projectFolder) && npm run build && popd
  displayName: 'npm run build'

